//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHEQUE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHEQUE()
        {
            this.TRANSACCIONES = new HashSet<TRANSACCIONES>();
        }
    
        public int CORRELATIVO_CHEQUE { get; set; }
        public Nullable<int> COD_PROVEEDOR { get; set; }
        public string ID_LINEA { get; set; }
        public string NOMBRE { get; set; }
        public string CONCEPTO_CHEQUE { get; set; }
        public double MONTO { get; set; }
        public Nullable<bool> ANULADO_CHEQUE { get; set; }
    
        public virtual LINEA_DE_PLANILLA LINEA_DE_PLANILLA { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACCIONES> TRANSACCIONES { get; set; }
    }
}
