//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMPRA()
        {
            this.INVENTARIO_MATERIAL = new HashSet<INVENTARIO_MATERIAL>();
            this.TRANSACCIONES = new HashSet<TRANSACCIONES>();
        }
    
        public int CORRELATIVO { get; set; }
        public Nullable<int> ID_COSMATERIAL { get; set; }
        public string ID_COSTO { get; set; }
        public Nullable<int> COD_PROVEEDOR { get; set; }
        public string TIPO_DOCU_COMPRA { get; set; }
        public string TIPO_PAGO_COMPRA { get; set; }
        public System.DateTime FECHA_EMISION { get; set; }
        public string CONCEPTO_COMPRA { get; set; }
        public string TIPO_DE_PAGO { get; set; }
        public double SUMA { get; set; }
        public double IVA { get; set; }
        public double TOTAL_COMPRA { get; set; }
        public Nullable<double> COMPRA_EXENTAS { get; set; }
        public Nullable<double> RETENCION_RENTA { get; set; }
        public Nullable<double> BONIFICACIONES { get; set; }
        public Nullable<double> RETENCION_DE_IVA { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual COSTO_INDIRECTO COSTO_INDIRECTO { get; set; }
        public virtual COTOS_DE_MATERIAL COTOS_DE_MATERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTARIO_MATERIAL> INVENTARIO_MATERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACCIONES> TRANSACCIONES { get; set; }
    }
}
