//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COSTO_INDIRECTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COSTO_INDIRECTO()
        {
            this.COMPRA = new HashSet<COMPRA>();
            this.PRODUCTO_TERMINADO = new HashSet<PRODUCTO_TERMINADO>();
        }
    
        public string ID_COSTO { get; set; }
        public Nullable<int> ID_PLANILLA { get; set; }
        public Nullable<double> COSTO_DE_MANO { get; set; }
        public Nullable<double> OTROS_COSTOS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA> COMPRA { get; set; }
        public virtual PLANILLA PLANILLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_TERMINADO> PRODUCTO_TERMINADO { get; set; }
    }
}
