//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COTOS_DE_MATERIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COTOS_DE_MATERIAL()
        {
            this.COMPRA = new HashSet<COMPRA>();
            this.PRODUCTO_TERMINADO = new HashSet<PRODUCTO_TERMINADO>();
        }
    
        public int ID_COSMATERIAL { get; set; }
        public Nullable<System.DateTime> FECHA_DE_INGRESO { get; set; }
        public double COSTO_DE_COMPRA { get; set; }
        public double COSTO_UNITARIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA> COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_TERMINADO> PRODUCTO_TERMINADO { get; set; }
    }
}
