//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOJA_DE_TRABAJO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOJA_DE_TRABAJO()
        {
            this.PLANILLA = new HashSet<PLANILLA>();
        }
    
        public string ID_HOJA { get; set; }
        public double SALARIO_HOR_NOMAL { get; set; }
        public Nullable<double> SALRIOHORASEXTRAS { get; set; }
        public Nullable<int> HORASTRABAJADAS { get; set; }
        public Nullable<double> HORASEXTRAS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANILLA> PLANILLA { get; set; }
    }
}
