//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO_MATERIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVENTARIO_MATERIAL()
        {
            this.PRODUCTO_EN_PROCESO = new HashSet<PRODUCTO_EN_PROCESO>();
        }
    
        public string COD_MATERIAL { get; set; }
        public Nullable<int> CORRELATIVO { get; set; }
        public string NOM_MATERIAL { get; set; }
        public string UNIDADES { get; set; }
        public Nullable<int> EXISTENCIA_ { get; set; }
    
        public virtual COMPRA COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_EN_PROCESO> PRODUCTO_EN_PROCESO { get; set; }
    }
}
