//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContable.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A50304_jorgemarro91Entities : DbContext
    {
        public DB_A50304_jorgemarro91Entities()
            : base("name=DB_A50304_jorgemarro91Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATALOGO_DE_PRODUCTO> CATALOGO_DE_PRODUCTO { get; set; }
        public virtual DbSet<CHEQUE> CHEQUE { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<COMPRA> COMPRA { get; set; }
        public virtual DbSet<COSTO_INDIRECTO> COSTO_INDIRECTO { get; set; }
        public virtual DbSet<COTOS_DE_MATERIAL> COTOS_DE_MATERIAL { get; set; }
        public virtual DbSet<CUENTA> CUENTA { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<HOJA_DE_TRABAJO> HOJA_DE_TRABAJO { get; set; }
        public virtual DbSet<INVENTARIO_MATERIAL> INVENTARIO_MATERIAL { get; set; }
        public virtual DbSet<KARDEX> KARDEX { get; set; }
        public virtual DbSet<LINEA_DE_PLANILLA> LINEA_DE_PLANILLA { get; set; }
        public virtual DbSet<PATRONO> PATRONO { get; set; }
        public virtual DbSet<PERIODO> PERIODO { get; set; }
        public virtual DbSet<PLANILLA> PLANILLA { get; set; }
        public virtual DbSet<PRODUCTO_EN_PROCESO> PRODUCTO_EN_PROCESO { get; set; }
        public virtual DbSet<PRODUCTO_TERMINADO> PRODUCTO_TERMINADO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<REMESAS> REMESAS { get; set; }
        public virtual DbSet<TRANSACCIONES> TRANSACCIONES { get; set; }
        public virtual DbSet<VENTA> VENTA { get; set; }
    }
}
