//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATRONO
    {
        public string IDPATRONO { get; set; }
        public string ID_LINEA { get; set; }
        public double ISSS { get; set; }
        public double AFP { get; set; }
    
        public virtual LINEA_DE_PLANILLA LINEA_DE_PLANILLA { get; set; }
    }
}
