//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANILLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANILLA()
        {
            this.COSTO_INDIRECTO = new HashSet<COSTO_INDIRECTO>();
            this.TRANSACCIONES = new HashSet<TRANSACCIONES>();
        }
    
        public int ID_PLANILLA { get; set; }
        public string DUI { get; set; }
        public string ID_LINEA { get; set; }
        public string ID_HOJA { get; set; }
        public System.DateTime FECHAPAGO { get; set; }
        public double DE_ISS_TRABA { get; set; }
        public Nullable<double> DESCUENTOS { get; set; }
        public Nullable<double> AFP_TRABAJADOR { get; set; }
        public Nullable<double> TOTAL_PLANILLA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COSTO_INDIRECTO> COSTO_INDIRECTO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual HOJA_DE_TRABAJO HOJA_DE_TRABAJO { get; set; }
        public virtual LINEA_DE_PLANILLA LINEA_DE_PLANILLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACCIONES> TRANSACCIONES { get; set; }
    }
}
