//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_TERMINADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO_TERMINADO()
        {
            this.PRODUCTO_EN_PROCESO = new HashSet<PRODUCTO_EN_PROCESO>();
        }
    
        public int CORRELATIVO_PRODUCTO { get; set; }
        public Nullable<int> NUMKARDEX { get; set; }
        public Nullable<int> ID_COSMATERIAL { get; set; }
        public string ID_COSTO { get; set; }
        public string DESCRIPCION_DEL_PRODUCTO_TERMINADO { get; set; }
        public int EXISTENCIA_PRODUCTO { get; set; }
    
        public virtual COSTO_INDIRECTO COSTO_INDIRECTO { get; set; }
        public virtual COTOS_DE_MATERIAL COTOS_DE_MATERIAL { get; set; }
        public virtual KARDEX KARDEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_EN_PROCESO> PRODUCTO_EN_PROCESO { get; set; }
    }
}
