//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_EN_PROCESO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO_EN_PROCESO()
        {
            this.INVENTARIO_MATERIAL = new HashSet<INVENTARIO_MATERIAL>();
            this.PRODUCTO_TERMINADO = new HashSet<PRODUCTO_TERMINADO>();
        }
    
        public string CORRELATIVO_PROCE { get; set; }
        public string ID_PRODUCTO { get; set; }
        public Nullable<System.DateTime> FECHA_DE_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_DE_DESPACHO { get; set; }
        public Nullable<int> CANTI_PROCESO { get; set; }
    
        public virtual CATALOGO_DE_PRODUCTO CATALOGO_DE_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTARIO_MATERIAL> INVENTARIO_MATERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO_TERMINADO> PRODUCTO_TERMINADO { get; set; }
    }
}
