//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REMESAS
    {
        public string CORRELATIVO_CHEQUE_REMESA { get; set; }
        public string CORRELATIVO_DOC { get; set; }
        public string A_NOMBRE { get; set; }
        public string CONCEPTO_REMESA { get; set; }
        public double MONTO_REMESA { get; set; }
        public Nullable<bool> ANULADO_REMESA { get; set; }
    
        public virtual VENTA VENTA { get; set; }
    }
}
