//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSACCIONES()
        {
            this.VENTA = new HashSet<VENTA>();
            this.COMPRA = new HashSet<COMPRA>();
        }
    
        public string NUM_TRANSACCION { get; set; }
        public string NUMPERIODO { get; set; }
        public string COD_CUENTA { get; set; }
        public Nullable<int> CORRELATIVO_CHEQUE { get; set; }
        public Nullable<int> ID_PLANILLA { get; set; }
        public string CONCEPTO { get; set; }
        public string CUENTA_CARGADA { get; set; }
        public string CUENTA_ABONAR { get; set; }
        public double MONTO_ABONADO { get; set; }
        public double MONTO_CARGADO { get; set; }
    
        public virtual CHEQUE CHEQUE { get; set; }
        public virtual CUENTA CUENTA { get; set; }
        public virtual PERIODO PERIODO { get; set; }
        public virtual PLANILLA PLANILLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA> VENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA> COMPRA { get; set; }
    }
}
