//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaContable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTA()
        {
            this.REMESAS = new HashSet<REMESAS>();
            this.TRANSACCIONES = new HashSet<TRANSACCIONES>();
        }
    
        public string CORRELATIVO_DOC { get; set; }
        public string ID_PRODUCTO { get; set; }
        public string ID_CLIENTE { get; set; }
        public Nullable<int> NUMKARDEX { get; set; }
        public string TIPO_DOCU_VENTA { get; set; }
        public string TIPO_PAGO { get; set; }
        public string CONCEPTO_DE_VENTA { get; set; }
        public double SUBTOTAL { get; set; }
        public Nullable<double> DESCUENTO { get; set; }
        public Nullable<double> GRAVADAS { get; set; }
        public Nullable<double> IVA { get; set; }
        public Nullable<double> IVA_PERSIVIDO { get; set; }
        public Nullable<double> IVA_RETENIDO { get; set; }
        public Nullable<double> VENTAS_EXENTAS { get; set; }
        public Nullable<double> TOTAL { get; set; }
    
        public virtual CATALOGO_DE_PRODUCTO CATALOGO_DE_PRODUCTO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual KARDEX KARDEX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REMESAS> REMESAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACCIONES> TRANSACCIONES { get; set; }
    }
}
